import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
        pathname: "/dyr5ihrer/**",
      },
    ],
  },
  async redirects() {
    return [
      // Consolidate all traffic to https://www.gatesroof.com (SEO canonical)
      {
        source: "/:path*",
        has: [{ type: "host", value: "gatesroof.com" }],
        destination: "https://www.gatesroof.com/:path*",
        permanent: true,
      },
      // Service area redirects (old /service-areas/{city}-co → /areas/{city})
      { source: "/service-areas/lakewood-co", destination: "/areas/lakewood", permanent: true },
      { source: "/service-areas/parker-co", destination: "/areas/parker", permanent: true },
      { source: "/service-areas/aurora-co", destination: "/areas/aurora", permanent: true },
      { source: "/service-areas/denver-co", destination: "/areas/denver", permanent: true },
      { source: "/service-areas/arvada-co", destination: "/areas/arvada", permanent: true },
      { source: "/service-areas/broomfield-co", destination: "/areas/broomfield", permanent: true },
      { source: "/service-areas/castle-rock-co", destination: "/areas/castle-rock", permanent: true },
      { source: "/service-areas/centennial-co", destination: "/areas/centennial", permanent: true },
      { source: "/service-areas/commerce-city-co", destination: "/areas/commerce-city", permanent: true },
      { source: "/service-areas/conifer-co", destination: "/areas/conifer", permanent: true },
      { source: "/service-areas/edgewater-co", destination: "/areas/edgewater", permanent: true },
      { source: "/service-areas/englewood-co", destination: "/areas/englewood", permanent: true },
      { source: "/service-areas/federal-heights-co", destination: "/areas/federal-heights", permanent: true },
      { source: "/service-areas/golden-co", destination: "/areas/golden", permanent: true },
      { source: "/service-areas/highlands-ranch-co", destination: "/areas/highlands-ranch", permanent: true },
      { source: "/service-areas/littleton-co", destination: "/areas/littleton", permanent: true },
      { source: "/service-areas/northglenn-co", destination: "/areas/northglenn", permanent: true },
      { source: "/service-areas/thornton-co", destination: "/areas/thornton", permanent: true },
      { source: "/service-areas/westminster-co", destination: "/areas/westminster", permanent: true },
      { source: "/service-areas/wheat-ridge-co", destination: "/areas/wheat-ridge", permanent: true },
      // Out-of-state pages that were indexed (redirect to homepage)
      { source: "/service-areas/las-vegas-nv", destination: "/", permanent: true },
      { source: "/service-areas/henderson-nv", destination: "/", permanent: true },
      { source: "/service-areas/enterprise-nv", destination: "/", permanent: true },
      { source: "/service-areas/saint-paul-mn", destination: "/", permanent: true },
      { source: "/service-areas/minneapolis-mn", destination: "/", permanent: true },
      { source: "/service-areas/spring-valley-nv", destination: "/", permanent: true },
      { source: "/service-areas/lockwood-mt", destination: "/", permanent: true },
      { source: "/service-areas/laurel-mt", destination: "/", permanent: true },
      { source: "/service-areas/worden-mt", destination: "/", permanent: true },
      { source: "/service-areas/park-city-mt", destination: "/", permanent: true },
      // Old about page
      { source: "/about-us", destination: "/about", permanent: true },
      // Catch-all for any other old service-areas URLs
      { source: "/service-areas/:slug", destination: "/areas/:slug", permanent: true },
      // Old service index pages
      { source: "/service-areas", destination: "/areas/lakewood", permanent: true },
      { source: "/services/residential-roofing", destination: "/services/roof-replacement", permanent: true },
      { source: "/services/general-contractor", destination: "/services/roof-replacement", permanent: true },
      { source: "/services/commercial-roofing", destination: "/services/roof-replacement", permanent: true },
      { source: "/services/insurance-claim-specialists", destination: "/services", permanent: true },
      { source: "/services/skylights", destination: "/services/windows", permanent: true },
      // Old tools
      { source: "/tools/roof-replacement-cost-estimator", destination: "/tools/repair-cost-estimator", permanent: true },
      // Old routes
      { source: "/regions", destination: "/areas/lakewood", permanent: true },
      { source: "/st-paul-minneapolis", destination: "/", permanent: true },
      // Old pages from previous site (Rebolt/legacy)
      { source: "/careers", destination: "/about", permanent: true },
      { source: "/residential-services", destination: "/services", permanent: true },
      { source: "/commercial-services", destination: "/services/roof-replacement", permanent: true },
      // Old FAQ format
      { source: "/roof-faq", destination: "/", permanent: true },
      { source: "/roof-faq/roofblog/:path*", destination: "/blog", permanent: true },
      { source: "/roof-faq/:id", destination: "/services", permanent: true },
      // Old blog posts that were indexed but no longer exist
      { source: "/blog/rooftop-revolution-exploring-the-cutting-edge-innovations-transforming-home-with-solar-roofing", destination: "/blog", permanent: true },
      { source: "/blog/pros-and-cons-of-different-roofing-styles-in-colorado-which-suits-you", destination: "/blog", permanent: true },
      { source: "/blog/more-essential-tips-for-finding-a-reliable-roofer-in-denver", destination: "/blog", permanent: true },
      { source: "/blog/red-flags-common-roofing-scams-targeting-colorado-residents", destination: "/blog", permanent: true },
      { source: "/blog/roof-claims-on-your-homeowners-insurance/:path*", destination: "/blog", permanent: true },
      // Old service URLs → correct service pages
      { source: "/services/roofing", destination: "/services", permanent: true },
      { source: "/services/gutters", destination: "/services/gutters/lakewood", permanent: true },
      { source: "/services/siding", destination: "/services", permanent: true },
      // Old pages → correct pages
      { source: "/get-a-quote", destination: "/contact", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/mission-statement", destination: "/about", permanent: true },
      { source: "/billings", destination: "/", permanent: true },
      { source: "/denver", destination: "/areas/denver", permanent: true },
      // Old project pages (specific before catch-all)
      { source: "/projects/transforming-homes-with-quality-siding-services", destination: "/services", permanent: true },
      { source: "/projects/transformative-home-painting-in-nevada", destination: "/services", permanent: true },
      { source: "/projects/:slug", destination: "/gallery", permanent: true },
      // Pruned neighborhood pages → parent city pages (March 2026 - doorway page risk reduction)
      { source: "/services/:service/denver/baker", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/gateway", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/hampden", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/university-hills", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/southmoor-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/hilltop", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/cory-merrill", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/platt-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/sunnyside", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/berkeley", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/villa-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/barnum", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/ruby-hill", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/harvey-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/bear-valley", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/regis", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/chaffee-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/globeville", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/elyria-swansea", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/cole", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/whittier", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/city-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/city-park-west", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/cheesman-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/speer", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/lincoln-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/athmar-park", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/overland", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/denver/mar-lee", destination: "/services/:service/denver", permanent: true },
      { source: "/services/:service/aurora/saddle-rock", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/tollgate-crossing", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/piney-creek", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/heather-ridge", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/mission-viejo", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/dayton-triangle", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/aurora-hills", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/side-creek", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/meadow-hills", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/sable-ridge", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/chambers-heights", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/aurora/fletcher", destination: "/services/:service/aurora", permanent: true },
      { source: "/services/:service/colorado-springs/northgate", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/old-colorado-city", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/manitou-springs-area", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/flying-horse", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/cordera", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/wolf-ranch", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/banning-lewis-ranch", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/stetson-hills", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/falcon", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/cimarron-hills", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/security-widefield", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/peterson-area", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/colorado-springs/powers", destination: "/services/:service/colorado-springs", permanent: true },
      { source: "/services/:service/lakewood/bear-creek-lakewood", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/lakewood/carmody", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/lakewood/morse-park", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/lakewood/eiber", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/lakewood/two-creeks", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/lakewood/foothills-lakewood", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/lakewood/union-square", destination: "/services/:service/lakewood", permanent: true },
      { source: "/services/:service/arvada/ralston-valley", destination: "/services/:service/arvada", permanent: true },
      { source: "/services/:service/arvada/leyden-rock", destination: "/services/:service/arvada", permanent: true },
      { source: "/services/:service/arvada/west-woods", destination: "/services/:service/arvada", permanent: true },
      { source: "/services/:service/arvada/whisper-creek", destination: "/services/:service/arvada", permanent: true },
      { source: "/services/:service/arvada/arvada-plaza", destination: "/services/:service/arvada", permanent: true },
      { source: "/services/:service/arvada/two-ponds", destination: "/services/:service/arvada", permanent: true },
      { source: "/services/:service/parker/idyllwilde", destination: "/services/:service/parker", permanent: true },
      { source: "/services/:service/parker/canterberry", destination: "/services/:service/parker", permanent: true },
      { source: "/services/:service/parker/lincoln-creek", destination: "/services/:service/parker", permanent: true },
      { source: "/services/:service/castle-rock/terrain", destination: "/services/:service/castle-rock", permanent: true },
      { source: "/services/:service/castle-rock/crystal-valley", destination: "/services/:service/castle-rock", permanent: true },
      { source: "/services/:service/castle-rock/founders-village", destination: "/services/:service/castle-rock", permanent: true },
      { source: "/services/:service/castle-rock/castlewood-ranch", destination: "/services/:service/castle-rock", permanent: true },
      { source: "/services/:service/highlands-ranch/eastridge", destination: "/services/:service/highlands-ranch", permanent: true },
      { source: "/services/:service/highlands-ranch/westridge", destination: "/services/:service/highlands-ranch", permanent: true },
      { source: "/services/:service/highlands-ranch/northridge", destination: "/services/:service/highlands-ranch", permanent: true },
      { source: "/services/:service/highlands-ranch/southridge", destination: "/services/:service/highlands-ranch", permanent: true },
      { source: "/services/:service/fort-collins/old-town-fort-collins", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/midtown-fort-collins", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/timnath", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/wellington", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/harmony", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/fossil-creek", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/front-range-village", destination: "/services/:service/fort-collins", permanent: true },
      { source: "/services/:service/fort-collins/mountain-vista", destination: "/services/:service/fort-collins", permanent: true },
    ];
  },
};

export default nextConfig;
