// FAQs for /services/storm-hail-damage.
//
// page.tsx (FAQPage JSON-LD) and content.tsx (the visible accordion) both read
// this array, so the marked-up Q/A cannot drift from what the page renders.
// page.tsx previously hand-maintained a second, abbreviated copy inside its
// JSON-LD; the wording here is the copy that was visible on the page.
export const FAQS: { q: string; a: string }[] = [
  { q: "How do I know if my roof has hail damage?", a: "Hail damage isn't always visible from the ground. Common signs include dented gutters, granule loss in your downspouts, and dings on roof vents or flashing. Even if your roof looks fine from the street, hail can compromise the shingle's integrity underneath. We've inspected thousands of roofs across the Denver metro after storms and the damage is almost always worse than it looks. We offer free inspections so you can know for certain." },
  { q: "Should I file with my insurance for storm damage?", a: "If the damage exceeds your deductible, filing is usually the right move. Colorado is one of the most hail prone states in the country, and most homeowner policies are designed to cover exactly this kind of damage. Our team has helped thousands of homeowners through the restoration process from initial inspection through final install. We document everything thoroughly and assist you through the claims process." },
  { q: "How quickly can you respond after a storm?", a: "Storm response is our top priority. With over 100 team members across Colorado's Front Range, we have the capacity to mobilize immediately after a storm hits. While other companies are booking out weeks, we're already on roofs getting inspections done." },
  { q: "Will my insurance cover the full cost of repairs?", a: "Whether repairs are covered depends on your specific policy and the cause of damage. We document every detail thoroughly with photos, measurements, and manufacturer specifications to support a complete and fair resolution. If additional documentation is needed, we provide it. We've assisted with over 7,204 roof projects across Colorado." },
  { q: "What should I do immediately after a hailstorm?", a: "Don't get on your roof. Document what you can see from the ground, take photos of any damage to gutters, siding, or windows, and call us for a free inspection. The sooner you get a professional assessment, the stronger your case will be. Colorado has a one year deadline to file with most carriers, but earlier is always better." },
  { q: "Do I need to pay anything out of pocket?", a: "If your claim is approved, your out-of-pocket is typically your policy deductible. The rest may be covered by your policy, depending on your specific coverage. We work with your insurance adjuster to help ensure the scope of work and pricing align so there are no surprises." },
  { q: "Can I choose my own contractor or does insurance pick one?", a: "You always have the right to choose your own contractor in Colorado. Your insurance company may suggest preferred vendors, but you are not required to use them. Choosing a quadruple manufacturer certified contractor like Gates Enterprises ensures your roof is installed to the highest standards with warranties that preferred vendor programs often can't match." },
  { q: "What if my insurance restoration gets denied?", a: "It happens, but it's not always the final answer. We can help you understand why coverage was denied and whether a re-inspection is worth pursuing. Having thorough documentation from a certified contractor can make a significant difference in outcomes." },
  { q: "How long do I have to file a hail damage claim in Colorado?", a: "Most Colorado homeowners insurance policies give you one year from the date of the storm to file a claim. After that window closes, you may lose your right to coverage entirely. Unrepaired hail damage also allows moisture intrusion that causes secondary damage your insurance may not cover. If your home was in a storm's path within the past year, call (720) 766-3377 for a free inspection before your filing window expires." },
  { q: "What size hail causes roof damage?", a: "Hail as small as 1 inch in diameter (about the size of a quarter) can damage standard asphalt shingles. At 1.5 inches and above, damage becomes significant and widespread. Colorado regularly produces hailstones of 2 inches or larger, which can destroy even relatively new roofs. Class 4 impact-resistant shingles are tested to withstand 2 inch steel ball impacts and are our top recommendation for Colorado homes." },
];
