// Service × City programmatic SEO data
// Gates Enterprises – Colorado Front Range

export interface CityData {
  city: string;
  slug: string;
  county: string;
  description: string;
  lat: number;
  lon: number;
  population?: number;
  hailRisk: "high" | "moderate" | "low";
  neighborhoods?: string[];
}

export interface ServiceData {
  service: string;
  slug: string;
  shortDesc: string;
  longDesc: string;
  parentSlug: string; // links to existing /services/[parentSlug] page
  process: { step: string; desc: string }[];
  faqs: { q: string; a: string }[];
}

// ---------------------------------------------------------------------------
// CITIES (65 Colorado Front Range cities)
// ---------------------------------------------------------------------------
export const cities: CityData[] = [
  {
    city: "Denver",
    slug: "denver",
    county: "Denver",
    description: "Colorado's capital city and the heart of the Front Range metro, Denver sits at exactly one mile above sea level where the Great Plains meet the Rocky Mountains.",
    lat: 39.7392,
    lon: -104.9903,
    population: 715522,
    hailRisk: "moderate",
    neighborhoods: ["Capitol Hill", "Highland", "Park Hill", "Washington Park", "Cherry Creek", "RiNo", "Stapleton", "Green Valley Ranch", "Montbello", "Baker"],
  },
  {
    city: "Aurora",
    slug: "aurora",
    county: "Arapahoe",
    description: "Stretching across three counties east of Denver, Aurora is Colorado's third-largest city and sits squarely in the Front Range hail corridor where storms intensify as they move off the Palmer Divide.",
    lat: 39.7294,
    lon: -104.8319,
    population: 386261,
    hailRisk: "high",
    neighborhoods: ["Southlands", "Tallyn's Reach", "Murphy Creek", "Saddle Rock", "Quincy Reservoir", "Original Aurora", "Del Mar Parkway", "Fitzsimons"],
  },
  {
    city: "Lakewood",
    slug: "lakewood",
    county: "Jefferson",
    description: "Lakewood sits along the western edge of the Denver metro at the base of the foothills in Jefferson County. As Gates Enterprises' home city, Lakewood is where our team has completed more roofing projects than anywhere else.",
    lat: 39.7047,
    lon: -105.0814,
    population: 155984,
    hailRisk: "moderate",
    neighborhoods: ["Green Mountain", "Belmar", "Union Square", "Bear Creek", "Alameda Gateway", "Eiber", "Morse Park"],
  },
  {
    city: "Arvada",
    slug: "arvada",
    county: "Jefferson",
    description: "Nestled between the foothills and the northern Denver metro, Arvada blends a historic Olde Town district with newer developments that frequently take direct hits from hail storms rolling south off the Boulder County line.",
    lat: 39.8028,
    lon: -105.0875,
    population: 124402,
    hailRisk: "moderate",
    neighborhoods: ["Olde Town", "Ralston Valley", "West Woods", "Leyden Rock", "Candelas", "Arvada Plaza"],
  },
  {
    city: "Westminster",
    slug: "westminster",
    county: "Adams",
    description: "Westminster spans Adams and Jefferson counties between Denver and Boulder, positioned along the US-36 corridor where it catches hail storms moving through the northern metro with regularity.",
    lat: 39.8367,
    lon: -105.0372,
    population: 116317,
    hailRisk: "moderate",
    neighborhoods: ["Bradburn Village", "Countryside", "Shaw Heights", "Church Ranch", "Hyland Village", "Sheridan Green"],
  },
  {
    city: "Thornton",
    slug: "thornton",
    county: "Adams",
    description: "Thornton is one of the fastest-growing cities in Adams County, stretching north along I-25 through open prairie that offers zero natural protection from hail storms barreling across the northern Front Range.",
    lat: 39.8680,
    lon: -104.9719,
    population: 141867,
    hailRisk: "high",
    neighborhoods: ["Todd Creek", "Thorncreek", "Eastlake", "Hunters Glen", "Trail Creek", "North Creek"],
  },
  {
    city: "Broomfield",
    slug: "broomfield",
    county: "Broomfield",
    description: "Broomfield is both a city and its own county, sitting at the crossroads of the Denver-Boulder corridor. The Interlocken business park and surrounding neighborhoods see frequent hail events during Colorado's spring storm season.",
    lat: 39.9205,
    lon: -105.0867,
    population: 74112,
    hailRisk: "moderate",
    neighborhoods: ["Anthem", "Broadlands", "McKay Landing", "Interlocken", "Wildgrass"],
  },
  {
    city: "Northglenn",
    slug: "northglenn",
    county: "Adams",
    description: "Northglenn is a compact city in Adams County wedged between Thornton and Federal Heights, where older housing stock from the 1960s and 70s means many roofs are at or past their expected lifespan.",
    lat: 39.8853,
    lon: -104.9872,
    population: 39286,
    hailRisk: "moderate",
    neighborhoods: ["Northglenn Marketplace", "Malley Heights", "Croke Reservoir", "Huron Park"],
  },
  {
    city: "Federal Heights",
    slug: "federal-heights",
    county: "Adams",
    description: "Federal Heights sits north of Denver near the I-25 and US-36 interchange in Adams County — a practical, working-class community where homeowners deserve the same certified quality contractors that serve more affluent areas.",
    lat: 39.8672,
    lon: -105.0136,
    population: 14382,
    hailRisk: "moderate",
    neighborhoods: ["Federal Center", "South Federal Heights", "North Federal Heights"],
  },
  {
    city: "Commerce City",
    slug: "commerce-city",
    county: "Adams",
    description: "Commerce City has rapidly transformed from industrial roots into a booming residential community in northeast Adams County. The flat, open terrain means hail storms lose nothing as they sweep across from the northeast.",
    lat: 39.8083,
    lon: -104.9339,
    population: 62539,
    hailRisk: "high",
    neighborhoods: ["Reunion", "Buffalo Run", "Tower Road", "Derby", "Rose Hill"],
  },
  {
    city: "Brighton",
    slug: "brighton",
    county: "Adams",
    description: "Brighton anchors the northeast corner of the Denver metro in Adams County, surrounded by agricultural land and new development. Its position at the edge of the metro makes it a direct target for hail storms moving across the open plains.",
    lat: 39.9853,
    lon: -104.8206,
    population: 41218,
    hailRisk: "high",
    neighborhoods: ["Bromley Park", "Prairie Center", "Brighton Crossings", "Longs Peak"],
  },
  {
    city: "Henderson",
    slug: "henderson",
    county: "Adams",
    description: "Henderson is a fast-growing unincorporated community in northeast Adams County, where new neighborhoods are rising on former farmland in an area known for intense spring and summer hailstorms.",
    lat: 39.9264,
    lon: -104.8700,
    population: 12000,
    hailRisk: "high",
    neighborhoods: ["Riverdale", "Henderson Farms", "E-470 Corridor"],
  },
  {
    city: "Littleton",
    slug: "littleton",
    county: "Arapahoe",
    description: "Littleton's charming historic downtown and established neighborhoods in southern Arapahoe County sit along the South Platte River, where older homes with mature trees are especially vulnerable to hail and wind damage.",
    lat: 39.6133,
    lon: -105.0166,
    population: 46208,
    hailRisk: "moderate",
    neighborhoods: ["Downtown Littleton", "Ketring Park", "Southbridge", "Heritage Village", "Progress Park"],
  },
  {
    city: "Englewood",
    slug: "englewood",
    county: "Arapahoe",
    description: "Englewood is a compact city surrounded by Denver on three sides in Arapahoe County. Its dense, established neighborhoods feature many mid-century homes where original roofing systems have long exceeded their expected lifespan.",
    lat: 39.6480,
    lon: -104.9878,
    population: 35515,
    hailRisk: "moderate",
    neighborhoods: ["Baker", "Bates-Logan", "Cinderella City", "Fort Logan"],
  },
  {
    city: "Sheridan",
    slug: "sheridan",
    county: "Arapahoe",
    description: "Sheridan is a small city of just over 6,000 residents in Arapahoe County, surrounded entirely by Englewood and Denver. Many homes here were built in the 1950s and 60s and need roofing systems that can handle Colorado weather.",
    lat: 39.6469,
    lon: -105.0250,
    population: 6358,
    hailRisk: "moderate",
    neighborhoods: ["Fort Logan", "Sheridan Estates"],
  },
  {
    city: "Centennial",
    slug: "centennial",
    county: "Arapahoe",
    description: "Centennial is an affluent south metro community in Arapahoe County known for excellent schools and well-maintained homes. The city sits along the transition zone where the metro meets the Palmer Divide, increasing hail exposure.",
    lat: 39.5807,
    lon: -104.8772,
    population: 108418,
    hailRisk: "high",
    neighborhoods: ["Smoky Hill", "Piney Creek", "Walnut Hills", "Southglenn", "The Streets at SouthGlenn", "Cherry Knolls"],
  },
  {
    city: "Highlands Ranch",
    slug: "highlands-ranch",
    county: "Douglas",
    description: "Highlands Ranch is Colorado's largest planned community, stretching across northern Douglas County with over 100,000 residents. Its elevated position along the Palmer Divide corridor makes it one of the most hail-impacted communities on the Front Range.",
    lat: 39.5519,
    lon: -104.9708,
    population: 105026,
    hailRisk: "high",
    neighborhoods: ["Backcountry", "Westridge", "Eastridge", "Northridge", "Highlands Point", "Town Center"],
  },
  {
    city: "Parker",
    slug: "parker",
    county: "Douglas",
    description: "Parker sits at the northern edge of the Palmer Divide in Douglas County, where elevation and geography combine to make it one of the most hail-prone cities in the entire United States.",
    lat: 39.5186,
    lon: -104.7614,
    population: 57706,
    hailRisk: "high",
    neighborhoods: ["Stonegate", "Stroh Ranch", "Idyllwilde", "Canterberry", "Pine Creek", "Motsenbocker"],
  },
  {
    city: "Castle Rock",
    slug: "castle-rock",
    county: "Douglas",
    description: "Castle Rock is the county seat of Douglas County, perched along the Palmer Divide at over 6,200 feet. This elevated position makes Castle Rock ground zero for Colorado's most severe hailstorms.",
    lat: 39.3722,
    lon: -104.8561,
    population: 73158,
    hailRisk: "high",
    neighborhoods: ["The Meadows", "Castle Oaks", "Crystal Valley", "Founders Village", "Plum Creek"],
  },
  {
    city: "Castle Pines",
    slug: "castle-pines",
    county: "Douglas",
    description: "Castle Pines is an upscale community in Douglas County known for its golf courses and luxury homes. Sitting along the Palmer Divide, its higher-end roofing systems face some of Colorado's most severe hail exposure.",
    lat: 39.4582,
    lon: -104.8950,
    population: 14296,
    hailRisk: "high",
    neighborhoods: ["Castle Pines Village", "Castle Pines North", "Lagae Ranch", "Happy Canyon"],
  },
  {
    city: "Lone Tree",
    slug: "lone-tree",
    county: "Douglas",
    description: "Lone Tree sits in northern Douglas County along the Park Meadows corridor, where upscale neighborhoods and the RidgeGate development face significant hail exposure from Palmer Divide storm systems.",
    lat: 39.5386,
    lon: -104.8953,
    population: 14253,
    hailRisk: "high",
    neighborhoods: ["RidgeGate", "Sweetwater", "Heritage Hills", "Acres Green"],
  },
  {
    city: "Greenwood Village",
    slug: "greenwood-village",
    county: "Arapahoe",
    description: "Greenwood Village is one of Colorado's wealthiest communities, home to the Denver Tech Center in Arapahoe County. Its high-value properties with premium roofing materials require contractors who understand manufacturer warranty specifications.",
    lat: 39.6172,
    lon: -104.9508,
    population: 16015,
    hailRisk: "moderate",
    neighborhoods: ["DTC", "The Preserve", "Village Center", "Cherry Hills Farm"],
  },
  {
    city: "Cherry Hills Village",
    slug: "cherry-hills-village",
    county: "Arapahoe",
    description: "Cherry Hills Village is Colorado's most exclusive residential community, where estates with complex roofing systems and premium materials require manufacturer-certified contractors for proper installation and warranty coverage.",
    lat: 39.6414,
    lon: -104.9586,
    population: 6786,
    hailRisk: "moderate",
    neighborhoods: ["Cherry Hills", "Charlou", "Buell Mansion", "Old Cherry Hills"],
  },
  {
    city: "Columbine",
    slug: "columbine",
    county: "Jefferson",
    description: "Columbine is an unincorporated community in southwest Jefferson County, tucked against the foothills. Its mix of 1970s-era and newer homes means a wide range of roofing conditions and replacement needs.",
    lat: 39.5878,
    lon: -105.0694,
    population: 24280,
    hailRisk: "moderate",
    neighborhoods: ["Columbine Hills", "Columbine Knolls", "Columbine West"],
  },
  {
    city: "Ken Caryl",
    slug: "ken-caryl",
    county: "Jefferson",
    description: "Ken Caryl is a master-planned community nestled against the foothills in southern Jefferson County. Homes here sit at the boundary between the metro area and the mountains, where wind-driven rain and occasional hail demand durable roofing systems.",
    lat: 39.5756,
    lon: -105.1125,
    population: 33624,
    hailRisk: "moderate",
    neighborhoods: ["North Ranch", "South Valley", "Traditions", "The Settlement", "Heirloom"],
  },
  {
    city: "Morrison",
    slug: "morrison",
    county: "Jefferson",
    description: "Morrison is a tiny mountain town at the mouth of Bear Creek Canyon in Jefferson County, home to Red Rocks Amphitheatre. Its foothill location means high wind exposure and unique roofing challenges from mountain weather patterns.",
    lat: 39.6536,
    lon: -105.1911,
    population: 428,
    hailRisk: "low",
    neighborhoods: ["Bear Creek", "Mount Vernon Canyon"],
  },
  {
    city: "Golden",
    slug: "golden",
    county: "Jefferson",
    description: "Golden sits at the base of the foothills where Clear Creek exits the mountains, home to the Colorado School of Mines and Coors Brewery. The transition from plains to mountains creates unique microclimate conditions for roofing.",
    lat: 39.7555,
    lon: -105.2211,
    population: 20399,
    hailRisk: "low",
    neighborhoods: ["North Table Mountain", "South Table Mountain", "Pleasant View", "Heritage Dells", "Fossil Trace"],
  },
  {
    city: "Wheat Ridge",
    slug: "wheat-ridge",
    county: "Jefferson",
    description: "Wheat Ridge is a quiet, established community in Jefferson County sandwiched between Lakewood and Arvada. Many homes here date to the 1950s and 60s, making roof condition assessments and timely replacement especially important.",
    lat: 39.7661,
    lon: -105.0772,
    population: 31889,
    hailRisk: "moderate",
    neighborhoods: ["Apel", "Panorama Heights", "Fruitdale", "Leppke", "Anderson Park"],
  },
  {
    city: "Edgewater",
    slug: "edgewater",
    county: "Jefferson",
    description: "Edgewater is a small city of about 5,500 residents completely surrounded by Lakewood and Wheat Ridge in Jefferson County. Its compact footprint means storm damage from a single hail event can affect nearly every home in town.",
    lat: 39.7536,
    lon: -105.0636,
    population: 5518,
    hailRisk: "moderate",
    neighborhoods: ["Edgewater Marketplace", "Sloan's Lake"],
  },
  {
    city: "Mountain View",
    slug: "mountain-view",
    county: "Jefferson",
    description: "Mountain View is an unincorporated community in Jefferson County between Lakewood and Golden, where residential areas transition into the foothills and homes face both hail exposure and mountain wind patterns.",
    lat: 39.7372,
    lon: -105.1339,
    population: 560,
    hailRisk: "moderate",
    neighborhoods: ["Applewood", "Sixth Avenue West"],
  },
  {
    city: "Superior",
    slug: "superior",
    county: "Boulder",
    description: "Superior is an upscale community perched on the elevated flatiron mesa between Denver and Boulder in Boulder County. Its exposed position along the US-36 corridor makes it particularly vulnerable to severe hail events.",
    lat: 39.9528,
    lon: -105.1686,
    population: 13094,
    hailRisk: "moderate",
    neighborhoods: ["Rock Creek", "Superior Townsite", "Original Superior", "McCaslin"],
  },
  {
    city: "Louisville",
    slug: "louisville",
    county: "Boulder",
    description: "Louisville is a charming community in eastern Boulder County consistently ranked among the best places to live in the U.S. Its mix of historic downtown homes and newer developments creates diverse roofing needs.",
    lat: 39.9778,
    lon: -105.1319,
    population: 21226,
    hailRisk: "moderate",
    neighborhoods: ["Old Town Louisville", "Coal Creek Ranch", "Hecla-Caledonia", "Centaur Village"],
  },
  {
    city: "Lafayette",
    slug: "lafayette",
    county: "Boulder",
    description: "Lafayette sits in eastern Boulder County along the US-287 corridor, where open agricultural land to the east provides no buffer against hail storms pushing west across the plains.",
    lat: 39.9936,
    lon: -105.0897,
    population: 30042,
    hailRisk: "moderate",
    neighborhoods: ["Old Town Lafayette", "Indian Peaks", "Blue Heron", "Sagebrush"],
  },
  {
    city: "Erie",
    slug: "erie",
    county: "Boulder",
    description: "Erie straddles the Boulder-Weld county line and has exploded in population over the past decade. Rapid new construction combined with Colorado hail exposure means many newer homes have already experienced storm damage.",
    lat: 40.0503,
    lon: -105.0500,
    population: 30038,
    hailRisk: "high",
    neighborhoods: ["Erie Commons", "Vista Ridge", "Flatiron Meadows", "Coal Creek"],
  },
  {
    city: "Longmont",
    slug: "longmont",
    county: "Boulder",
    description: "Longmont is a diverse city in northern Boulder County situated between the foothills and the open plains. The 2023 hail event that caused widespread damage across the city demonstrated Longmont's significant hail exposure.",
    lat: 40.1672,
    lon: -105.1019,
    population: 98885,
    hailRisk: "high",
    neighborhoods: ["Old Town Longmont", "Prospect", "Hover Acres", "Twin Peaks", "Garden Acres", "Clover Basin"],
  },
  {
    city: "Loveland",
    slug: "loveland",
    county: "Larimer",
    description: "Loveland sits in the Big Thompson Valley in Larimer County, known as the Sweetheart City. Its northern Front Range location places it in the path of severe storms that develop along the Cheyenne Ridge and push southward.",
    lat: 40.3978,
    lon: -105.0750,
    population: 76378,
    hailRisk: "high",
    neighborhoods: ["Centerra", "Boise", "Lake Loveland Estates", "Mariana Butte", "Winona"],
  },
  {
    city: "Fort Collins",
    slug: "fort-collins",
    county: "Larimer",
    description: "Fort Collins is northern Colorado's largest city, home to Colorado State University in Larimer County. The July 2023 hail event that dropped baseball-sized stones across the city proved that Fort Collins faces significant severe weather risk.",
    lat: 40.5853,
    lon: -105.0844,
    population: 169810,
    hailRisk: "high",
    neighborhoods: ["Old Town", "Midtown", "Harmony Corridor", "Timnath", "Fossil Creek", "Mail Creek"],
  },
  {
    city: "Windsor",
    slug: "windsor",
    county: "Weld",
    description: "Windsor straddles the Larimer-Weld county line east of Fort Collins, where open plains and the Rawhide Flats create perfect conditions for severe thunderstorms and large hail events.",
    lat: 40.4775,
    lon: -104.9014,
    population: 36491,
    hailRisk: "high",
    neighborhoods: ["Water Valley", "RainDance", "Highland Meadows", "Pelican Lakes"],
  },
  {
    city: "Greeley",
    slug: "greeley",
    county: "Weld",
    description: "Greeley is the county seat of Weld County and a major agricultural hub on the northeastern Front Range. The flat terrain and eastern plains location put Greeley in the direct path of some of Colorado's most severe hail events.",
    lat: 40.4233,
    lon: -104.7091,
    population: 108795,
    hailRisk: "high",
    neighborhoods: ["West Greeley", "Glenmere Park", "Cranford", "Poudre River Trail", "Promontory"],
  },
  {
    city: "Evans",
    slug: "evans",
    county: "Weld",
    description: "Evans is a growing city adjacent to Greeley in Weld County, where affordable housing and rapid development meet some of the highest hail frequencies on the entire Front Range.",
    lat: 40.3764,
    lon: -104.6922,
    population: 22165,
    hailRisk: "high",
    neighborhoods: ["Riverside Park", "Del Camino Junction", "Evans Town Center"],
  },
  {
    city: "Johnstown",
    slug: "johnstown",
    county: "Weld",
    description: "Johnstown sits in western Weld County along I-25 between Loveland and Longmont, an area experiencing explosive residential growth. New subdivisions on former farmland face wide-open hail exposure.",
    lat: 40.3364,
    lon: -104.9119,
    population: 17264,
    hailRisk: "high",
    neighborhoods: ["Thompson River Ranch", "Thompson Crossing", "Brookstone"],
  },
  {
    city: "Firestone",
    slug: "firestone",
    county: "Weld",
    description: "Firestone is a rapidly growing town in southwestern Weld County, where new housing developments spread across open prairie that offers no natural protection from the severe hail events common to this part of the Front Range.",
    lat: 40.1125,
    lon: -104.9367,
    population: 17374,
    hailRisk: "high",
    neighborhoods: ["Barefoot Lakes", "Firestone Meadows", "Saddleback"],
  },
  {
    city: "Frederick",
    slug: "frederick",
    county: "Weld",
    description: "Frederick sits adjacent to Firestone in southwestern Weld County, a former mining town transformed into a suburban community. Rapid development and open terrain combine for significant hail exposure.",
    lat: 40.0992,
    lon: -104.9372,
    population: 15218,
    hailRisk: "high",
    neighborhoods: ["Wyndham Hill", "Silver Peaks", "Frederick Town Center"],
  },
  {
    city: "Dacono",
    slug: "dacono",
    county: "Weld",
    description: "Dacono is a small town between Frederick and Fort Lupton in Weld County, experiencing rapid growth. New construction on flat, exposed terrain makes hail damage a near-certainty within the first few years of homeownership.",
    lat: 40.0836,
    lon: -104.9394,
    population: 6111,
    hailRisk: "high",
    neighborhoods: ["Summit View Estates", "Weld County Road 8"],
  },
  {
    city: "Lochbuie",
    slug: "lochbuie",
    county: "Weld",
    description: "Lochbuie is a small but rapidly growing community in southwestern Weld County northeast of Brighton. The open agricultural landscape surrounding the town provides no shelter from the severe thunderstorms and hail events common to the area.",
    lat: 40.0067,
    lon: -104.7206,
    population: 7590,
    hailRisk: "high",
    neighborhoods: ["Lochbuie Station", "Thomas Farms"],
  },
  {
    city: "Bennett",
    slug: "bennett",
    county: "Adams",
    description: "Bennett is a small farming community in far eastern Adams County along I-70, where the wide-open plains and higher elevation create conditions for severe supercell thunderstorms with damaging hail.",
    lat: 39.7589,
    lon: -104.4283,
    population: 2779,
    hailRisk: "high",
    neighborhoods: ["Antelope Hills", "Bennett Ranch"],
  },
  {
    city: "Strasburg",
    slug: "strasburg",
    county: "Adams",
    description: "Strasburg is a rural community in eastern Adams County along I-70, known for its equestrian culture and wide-open prairie. Homes here face extreme hail exposure with no urban heat island or terrain features to weaken storms.",
    lat: 39.7383,
    lon: -104.3236,
    population: 2832,
    hailRisk: "high",
    neighborhoods: ["Strasburg Village", "Box Elder Creek"],
  },
  {
    city: "Elizabeth",
    slug: "elizabeth",
    county: "Elbert",
    description: "Elizabeth is a small town in Elbert County on the Palmer Divide, sitting at over 6,500 feet. Its Palmer Divide location makes it one of the most hail-prone communities in Colorado, with multiple severe events most years.",
    lat: 39.3606,
    lon: -104.5958,
    population: 1694,
    hailRisk: "high",
    neighborhoods: ["Running Creek", "Elizabeth Town Center"],
  },
  {
    city: "Franktown",
    slug: "franktown",
    county: "Douglas",
    description: "Franktown is an unincorporated community in eastern Douglas County along the Palmer Divide, surrounded by ranch land and acreage properties. Its high-elevation position on the Divide makes severe hail a regular occurrence.",
    lat: 39.3875,
    lon: -104.7464,
    population: 580,
    hailRisk: "high",
    neighborhoods: ["Ponderosa Park", "Cherry Creek Valley"],
  },
  {
    city: "Sedalia",
    slug: "sedalia",
    county: "Douglas",
    description: "Sedalia is a small unincorporated community in western Douglas County at the entrance to Roxborough State Park. Its position where the foothills meet the Palmer Divide creates unpredictable weather patterns and significant storm exposure.",
    lat: 39.4403,
    lon: -105.0894,
    population: 200,
    hailRisk: "moderate",
    neighborhoods: ["Roxborough", "Jarre Canyon"],
  },
  {
    city: "Conifer",
    slug: "conifer",
    county: "Jefferson",
    description: "Conifer is a mountain community in Jefferson County along US-285 at approximately 8,200 feet elevation. Mountain homes face unique roofing challenges including extreme UV exposure, heavy snow loads, and wind-driven ice damage.",
    lat: 39.5172,
    lon: -105.3408,
    population: 21973,
    hailRisk: "low",
    neighborhoods: ["Aspen Park", "Blue Creek", "Kings Valley", "Elk Creek"],
  },
  {
    city: "Evergreen",
    slug: "evergreen",
    county: "Jefferson",
    description: "Evergreen is a mountain community in Jefferson County nestled in Bear Creek Canyon at 7,200 feet. Its mountain setting means roofs must handle heavy snow, pine needle accumulation, and extreme freeze-thaw cycles.",
    lat: 39.6333,
    lon: -105.3172,
    population: 14636,
    hailRisk: "low",
    neighborhoods: ["Bergen Park", "El Rancho", "Hiwan", "Upper Bear Creek", "Soda Creek"],
  },
  {
    city: "Idaho Springs",
    slug: "idaho-springs",
    county: "Clear Creek",
    description: "Idaho Springs is a historic mining town in Clear Creek County along I-70 at 7,500 feet. The narrow canyon setting and mountain elevation create unique roofing demands including heavy snowfall, ice dams, and extreme wind.",
    lat: 39.7425,
    lon: -105.5136,
    population: 1833,
    hailRisk: "low",
    neighborhoods: ["Downtown Idaho Springs", "Virginia Canyon"],
  },
  {
    city: "Georgetown",
    slug: "georgetown",
    county: "Clear Creek",
    description: "Georgetown is a well-preserved Victorian mining town in Clear Creek County at 8,500 feet. Historic preservation requirements and extreme mountain weather make roofing work here technically demanding.",
    lat: 39.7061,
    lon: -105.6975,
    population: 1095,
    hailRisk: "low",
    neighborhoods: ["Georgetown Historic District", "Silver Plume"],
  },
  {
    city: "Bailey",
    slug: "bailey",
    county: "Park",
    description: "Bailey is a mountain community along US-285 in Park County at 7,700 feet, where forested mountain lots and high-altitude conditions create distinct roofing challenges including wildfire risk, snow loads, and UV degradation.",
    lat: 39.4058,
    lon: -105.4758,
    population: 8842,
    hailRisk: "low",
    neighborhoods: ["Elk Creek", "Deer Creek", "Crow Hill"],
  },
  {
    city: "Monument",
    slug: "monument",
    county: "El Paso",
    description: "Monument sits atop the Palmer Divide in northern El Paso County at 6,900 feet — the geographic high point between Denver and Colorado Springs. This location makes Monument one of the most hail-impacted towns in North America.",
    lat: 39.0917,
    lon: -104.8728,
    population: 7691,
    hailRisk: "high",
    neighborhoods: ["Jackson Creek", "Promontory Pointe", "Forest Lakes", "King's Deer"],
  },
  {
    city: "Palmer Lake",
    slug: "palmer-lake",
    county: "El Paso",
    description: "Palmer Lake is a small mountain town at the crest of the Palmer Divide in El Paso County, where severe hailstorms develop with alarming frequency due to the orographic lifting effect along the Divide.",
    lat: 39.1222,
    lon: -104.9178,
    population: 2816,
    hailRisk: "high",
    neighborhoods: ["Glen Park", "Lakeview Heights"],
  },
  {
    city: "Fountain",
    slug: "fountain",
    county: "El Paso",
    description: "Fountain is a growing community south of Colorado Springs in El Paso County, near Fort Carson. Military families and new residential construction create consistent demand for quality roofing services.",
    lat: 38.6822,
    lon: -104.7008,
    population: 30333,
    hailRisk: "high",
    neighborhoods: ["Mesa Ridge", "Countryside", "Fountain Mesa"],
  },
  {
    city: "Manitou Springs",
    slug: "manitou-springs",
    county: "El Paso",
    description: "Manitou Springs is a quirky mountain town nestled at the base of Pikes Peak in El Paso County. Steep terrain, historic buildings, and mountain weather patterns make roofing projects here technically challenging.",
    lat: 38.8586,
    lon: -104.9175,
    population: 5393,
    hailRisk: "moderate",
    neighborhoods: ["Old Colorado City", "Crystal Hills", "Pikes Peak"],
  },
  {
    city: "Colorado Springs",
    slug: "colorado-springs",
    county: "El Paso",
    description: "Colorado Springs is the state's second-largest city, spread across the base of Pikes Peak in El Paso County. The city's eastern neighborhoods face severe hail exposure while western areas near the mountain experience intense wind events.",
    lat: 38.8339,
    lon: -104.8214,
    population: 478961,
    hailRisk: "high",
    neighborhoods: ["Briargate", "Northgate", "Old Colorado City", "Broadmoor", "Stetson Hills", "Falcon", "Powers Corridor", "Rockrimmon"],
  },
  {
    city: "Pueblo",
    slug: "pueblo",
    county: "Pueblo",
    description: "Pueblo is a city of over 112,000 in southern Colorado along the Arkansas River. Hot summers and occasional severe thunderstorms moving off the Wet Mountains create unique roofing challenges in this southern Front Range city.",
    lat: 38.2544,
    lon: -104.6091,
    population: 112368,
    hailRisk: "moderate",
    neighborhoods: ["Pueblo West", "Belmont", "Mesa Junction", "Aberdeen", "Northside"],
  },
  {
    city: "Boulder",
    slug: "boulder",
    county: "Boulder",
    description: "Boulder sits against the dramatic Flatirons at the base of the Rocky Mountains in Boulder County. While the foothills provide some hail protection, Boulder's unique downslope windstorms — known as Chinook winds — create extreme roofing stress.",
    lat: 40.0150,
    lon: -105.2705,
    population: 105673,
    hailRisk: "moderate",
    neighborhoods: ["North Boulder", "South Boulder", "University Hill", "Gunbarrel", "Table Mesa", "Mapleton Hill", "Wonderland"],
  },
  {
    city: "Nederland",
    slug: "nederland",
    county: "Boulder",
    description: "Nederland is a mountain town at 8,200 feet in Boulder County, known for Frozen Dead Guy Days and its bohemian community. Extreme mountain weather, heavy snow loads, and high UV exposure at altitude demand robust roofing systems.",
    lat: 39.9614,
    lon: -105.5108,
    population: 1543,
    hailRisk: "low",
    neighborhoods: ["Caribou", "Eldora", "Rainbow Lakes"],
  },
  {
    city: "Lyons",
    slug: "lyons",
    county: "Boulder",
    description: "Lyons is a small town at the confluence of the North and South St. Vrain Creeks in Boulder County, known for its sandstone architecture and music festivals. After the devastating 2013 floods, resilient building practices are especially valued here.",
    lat: 40.2247,
    lon: -105.2714,
    population: 2033,
    hailRisk: "moderate",
    neighborhoods: ["Old Town Lyons", "Apple Valley", "Stone Canyon"],
  },
];

// ---------------------------------------------------------------------------
// SERVICES (8 services for programmatic pages)
// ---------------------------------------------------------------------------
export const services: ServiceData[] = [
  {
    service: "Roof Replacement",
    slug: "roof-replacement",
    parentSlug: "roof-replacement",
    shortDesc: "Full tear-off and certified installation with manufacturer warranties up to 50 years.",
    longDesc: "A roof replacement is one of the most significant investments you'll make in your home. Gates Enterprises performs complete tear-offs down to the deck, inspects and repairs sheathing as needed, and installs a full roofing system — not just shingles. Our certified installations include synthetic underlayment, ice and water shield in vulnerable areas, proper ventilation, and manufacturer-specified starter strips and ridge caps.\n\nAs a quadruple manufacturer-certified contractor — GAF Master Elite, Owens Corning Platinum Preferred, Malarkey Emerald Pro, and CertainTeed Shingle Master — we can install premium shingle systems from all four major manufacturers and offer the highest available warranty tiers on every project. Most residential replacements are completed in a single day.",
    process: [
      { step: "Free Inspection", desc: "We inspect your roof, document its condition, and provide an honest assessment of whether repair or replacement is the right move." },
      { step: "Material Selection", desc: "Choose from GAF, Owens Corning, Malarkey, or CertainTeed shingle systems. We explain the differences and help you select the best fit for your budget and goals." },
      { step: "Complete Tear-Off", desc: "We remove every layer down to the deck. No shortcuts, no layovers. This lets us inspect the sheathing and address any hidden issues." },
      { step: "System Installation", desc: "Full roofing system installation: underlayment, ice and water shield, drip edge, ventilation, shingles, and ridge caps — all to manufacturer specifications." },
      { step: "Final Inspection & Warranty", desc: "We walk the roof, clean the property, and register your manufacturer warranty. You receive full documentation of everything installed." },
    ],
    faqs: [
      { q: "How long does a roof replacement take?", a: "Most residential roof replacements are completed in a single day. Larger or more complex roofs may take two days. We'll give you a specific timeline during your estimate." },
      { q: "What does a roof replacement cost in Colorado?", a: "Cost varies based on roof size, pitch, material choice, and deck condition. Colorado residential replacements typically range from $10,000 to $30,000 for standard homes. Insurance often covers storm-damaged roofs minus your deductible." },
      { q: "Can I stay home during the replacement?", a: "Yes. We ask that you move vehicles out of the driveway and let us know about pets. The work is loud but we handle everything outside." },
      { q: "What warranty do I get?", a: "As a quadruple-certified contractor, we can offer the highest warranty tiers from all four major manufacturers — including GAF Golden Pledge (25-year workmanship) and Owens Corning Platinum Protection." },
      { q: "Do you handle the permit?", a: "Yes. We pull all required permits and coordinate county inspections on every project. The permit cost is included in your estimate." },
    ],
  },
  {
    service: "Storm & Hail Damage Repair",
    slug: "storm-hail-damage",
    parentSlug: "storm-hail-damage",
    shortDesc: "Free storm damage inspections and full insurance restoration for hail and wind damage.",
    longDesc: "Colorado's Front Range experiences more damaging hailstorms than almost anywhere else in the country. When a storm hits your neighborhood, your roof may have sustained damage that isn't visible from the ground — dented shingles, cracked granule surfaces, compromised seals, and bruised underlayment that will lead to leaks within months.\n\nGates Enterprises provides free, thorough storm damage inspections. We document every point of impact with photographs and measurements that your insurance company needs to process your claim. Our team has managed thousands of insurance restoration projects and knows exactly what adjusters look for. We handle the entire process from initial inspection through final supplement, so you get the full scope of work your policy covers.",
    process: [
      { step: "Free Storm Inspection", desc: "We inspect your roof, siding, gutters, and exterior for all storm damage. Every finding is photographed and documented." },
      { step: "Insurance Claim Filing", desc: "We help you file your claim with detailed documentation. Our reports are formatted the way adjusters need to see them." },
      { step: "Adjuster Meeting", desc: "We meet your insurance adjuster on-site to walk the roof together, ensuring nothing is missed in their assessment." },
      { step: "Full Restoration", desc: "Once approved, we complete all repairs or replacement to manufacturer specifications. Same certified quality as any other project." },
      { step: "Supplement if Needed", desc: "If the initial approval doesn't cover the full scope of damage, we prepare and submit supplements with additional documentation." },
    ],
    faqs: [
      { q: "Does insurance cover hail damage?", a: "Yes. Colorado homeowners insurance typically covers hail damage under your dwelling coverage. You're responsible for your deductible — Gates Enterprises handles everything else." },
      { q: "How do I know if I have hail damage?", a: "Most hail damage isn't visible from the ground. Look for dented gutters, chipped paint on window sills, or damaged patio furniture. The only way to know for sure is a professional roof inspection." },
      { q: "Is the inspection really free?", a: "Completely free with no obligation. We'll show you exactly what we find and give you an honest assessment. If there's no damage, we'll tell you." },
      { q: "How long do I have to file a claim?", a: "Most Colorado insurance policies have a 1-year window from the date of the storm. Don't wait — filing promptly gives you the best chance of full coverage." },
      { q: "What if my claim is denied?", a: "We fight for you. Our team has overturned many denied claims by providing additional documentation and evidence. We know what adjusters need to see." },
    ],
  },
  {
    service: "Roof Repair",
    slug: "roof-repair",
    parentSlug: "roof-repair",
    shortDesc: "Fast leak repair, emergency tarping, and honest assessments when full replacement isn't necessary.",
    longDesc: "Not every roof issue requires a full replacement. Leaks, missing shingles, flashing failures, and minor storm damage can often be repaired — and Gates Enterprises will tell you honestly whether repair or replacement is the right call. We don't push replacements on roofs that still have useful life remaining.\n\nOur repair services cover everything from emergency tarping during active leaks to precision flashing repairs around chimneys, vents, and skylights. We use the same manufacturer-specified materials and installation practices on repairs that we use on full replacements, because a proper repair should last for years — not just until the next storm.",
    process: [
      { step: "Inspection & Diagnosis", desc: "We identify the source of the problem — which is often not directly where the leak appears inside your home." },
      { step: "Honest Assessment", desc: "We tell you whether repair makes sense or if replacement is the better investment. No pressure either way." },
      { step: "Targeted Repair", desc: "We fix the specific issue using manufacturer-specified materials. No quick patches that fail in six months." },
      { step: "Verification", desc: "We verify the repair is sound, clean up completely, and document what was done for your records." },
    ],
    faqs: [
      { q: "Is it worth repairing an old roof?", a: "It depends. If your roof has 5+ years of life remaining and the damage is isolated, repair is often the smart choice. If damage is widespread or the roof is near end of life, replacement saves money long-term." },
      { q: "Can you fix an active leak quickly?", a: "Yes. We provide emergency tarping and fast leak repair. Call us at (720) 766-3377 and we'll get someone out as quickly as possible." },
      { q: "Do repairs come with a warranty?", a: "Yes. All our repair work is warranted. The specific terms depend on the scope of the repair and materials used." },
      { q: "Will a repair show on my roof?", a: "We match materials as closely as possible. On newer roofs, repairs are usually invisible. On older roofs, there may be a slight color variation due to weathering." },
    ],
  },
  {
    service: "Siding Installation & Repair",
    slug: "siding",
    parentSlug: "siding-exterior",
    shortDesc: "James Hardie fiber cement, vinyl, and wood siding installation and repair for Colorado homes.",
    longDesc: "Your siding is the first line of defense between your home and Colorado's demanding weather — hail, wind, UV radiation, and dramatic temperature swings. Damaged or aging siding doesn't just look bad; it allows moisture intrusion that can cause structural damage, mold growth, and energy loss.\n\nGates Enterprises installs and repairs James Hardie fiber cement, premium vinyl, and wood siding systems. As part of our exterior restoration services, we can coordinate siding work with roof replacement and gutter installation for a complete exterior transformation. Our crews follow manufacturer installation specifications on every project, and we handle all county permits and inspections.",
    process: [
      { step: "Exterior Assessment", desc: "We inspect your current siding for damage, moisture intrusion, and structural issues behind the panels." },
      { step: "Material & Style Selection", desc: "Choose from James Hardie fiber cement, vinyl, or wood options. We bring samples and help you select colors and profiles." },
      { step: "Preparation & Removal", desc: "We remove old siding, inspect and repair sheathing and moisture barriers, and ensure a solid substrate for the new installation." },
      { step: "Professional Installation", desc: "New siding installed to manufacturer specifications with proper flashing, caulking, and trim details." },
      { step: "Cleanup & Inspection", desc: "Final walkthrough to ensure everything meets our standards. We handle all debris removal and cleanup." },
    ],
    faqs: [
      { q: "Does insurance cover siding damage?", a: "If the damage was caused by a covered event like hail or wind, yes. We include siding in our storm damage inspections and help with the insurance claim process." },
      { q: "What siding material is best for Colorado?", a: "James Hardie fiber cement is our top recommendation for Colorado. It's resistant to hail, doesn't warp in temperature swings, and holds paint well at altitude. It also has Class A fire rating — important in wildfire-prone areas." },
      { q: "Can you match my existing siding?", a: "For repairs, we match the profile, texture, and color as closely as possible. For older siding that's been discontinued, we can often find close alternatives." },
      { q: "How long does siding installation take?", a: "A full siding installation typically takes 1-2 weeks depending on the size of your home and complexity. Repairs are usually completed in 1-2 days." },
      { q: "Can you do siding and roof at the same time?", a: "Absolutely. Coordinating both projects saves time, reduces disruption, and often saves money. Many insurance claims cover both roof and siding from the same storm event." },
    ],
  },
  {
    service: "Gutter Installation",
    slug: "gutters",
    parentSlug: "gutters-guards",
    shortDesc: "Seamless aluminum gutter fabrication and installation with gutter guard options.",
    longDesc: "Gutters aren't glamorous, but they're critical to protecting your home's foundation, siding, and landscaping from water damage. In Colorado, where afternoon thunderstorms can dump an inch of rain in minutes, properly sized and installed gutters channel that water safely away from your home.\n\nGates Enterprises fabricates seamless aluminum gutters on-site to the exact measurements of your roofline — no seams means no weak points where leaks develop. We install 5-inch and 6-inch gutter systems with properly sized downspouts, and we offer gutter guard systems to prevent the leaf and debris clogs that lead to overflow and ice dams during Colorado winters.",
    process: [
      { step: "Measurement & Planning", desc: "We measure your roofline and calculate proper gutter sizing based on roof area, pitch, and local rainfall rates." },
      { step: "On-Site Fabrication", desc: "Seamless gutters are formed on-site from continuous coils of aluminum, cut to the exact length of each run — no seams to leak." },
      { step: "Secure Installation", desc: "Hidden hanger brackets spaced at 24-inch intervals (or closer on long runs) for maximum strength against snow and ice loads." },
      { step: "Downspout Routing", desc: "Downspouts are strategically placed and routed to direct water away from your foundation, preventing basement and crawlspace issues." },
      { step: "Gutter Guard Option", desc: "We offer micro-mesh and surface-tension gutter guards that keep debris out while allowing full water flow." },
    ],
    faqs: [
      { q: "Why seamless gutters over sectional?", a: "Seams are the #1 failure point in gutter systems. Seamless gutters are formed from one continuous piece per run, eliminating joints where leaks develop. They also look cleaner." },
      { q: "Are gutter guards worth it in Colorado?", a: "If you have trees near your home, absolutely. Clogged gutters cause ice dams in winter (a major problem in Colorado) and overflow during summer storms. Guards pay for themselves by eliminating maintenance and preventing damage." },
      { q: "What size gutters do I need?", a: "Most Colorado homes use 5-inch gutters with 2x3 downspouts. Homes with steep roofs or large roof areas may need 6-inch gutters with 3x4 downspouts. We calculate the correct size for your specific home." },
      { q: "Does insurance cover gutter replacement?", a: "If your gutters were damaged by a covered event like hail or falling tree limbs, yes. Gutters are typically included in storm damage claims alongside roof and siding." },
    ],
  },
  {
    service: "Roof Inspection",
    slug: "roof-inspection",
    parentSlug: "roof-replacement",
    shortDesc: "Comprehensive roof inspections for storm damage, real estate transactions, and preventive maintenance.",
    longDesc: "A professional roof inspection is the smartest investment you can make in your home's most important protective system. Whether you're checking for storm damage after a hail event, buying or selling a home, or simply want to know the current condition of your roof, Gates Enterprises provides detailed, documented inspections that give you the full picture.\n\nOur inspectors are trained to identify issues that most homeowners — and many general contractors — miss: granule loss patterns that indicate hail impact, lifted flashing seals, improper ventilation causing premature aging, and early signs of moisture intrusion. Every inspection includes a written report with photographs, condition assessment, and our honest recommendation on next steps.",
    process: [
      { step: "Schedule Your Inspection", desc: "Call us or submit a request online. We schedule at a time that works for you — inspections take approximately 45-60 minutes." },
      { step: "Exterior Assessment", desc: "We inspect the roof surface, flashing, vents, gutters, and all penetration points. Every finding is photographed." },
      { step: "Attic Inspection", desc: "When accessible, we inspect the attic for proper ventilation, insulation condition, and any signs of moisture intrusion." },
      { step: "Detailed Report", desc: "You receive a written report with photos, condition ratings, estimated remaining life, and our honest recommendation." },
    ],
    faqs: [
      { q: "How much does a roof inspection cost?", a: "Storm damage inspections are always free. For real estate and maintenance inspections, call us for current pricing. The cost of an inspection is a fraction of what undetected damage can cost if left unaddressed." },
      { q: "How often should I get my roof inspected?", a: "We recommend annual inspections plus after any significant hail or wind event. Colorado weather is hard on roofs — catching small issues early prevents expensive problems." },
      { q: "I'm buying a home. Should I get a roof inspection?", a: "Absolutely. A general home inspector checks the roof briefly, but a specialist inspection by a certified roofing contractor provides far more detail. This can save you thousands in unexpected repairs after closing." },
      { q: "Will you find damage even if I can't see any from the ground?", a: "Yes. Most hail damage and early-stage failures are invisible from the ground. We inspect every roof from on top, at close range, where damage is visible." },
    ],
  },
  {
    service: "Insurance Claim Assistance",
    slug: "insurance-claims",
    parentSlug: "insurance-claims",
    shortDesc: "Full insurance restoration support — from initial claim filing through final supplement approval.",
    longDesc: "Navigating a homeowners insurance claim after storm damage is stressful and confusing. Insurance companies have teams of adjusters and estimators working for their interests — you deserve someone working for yours. Gates Enterprises has managed thousands of insurance restoration projects across the Colorado Front Range and knows exactly how the process works.\n\nOur Xactimate-certified estimators speak the same language as insurance adjusters. We document damage thoroughly, prepare estimates in the format adjusters require, meet adjusters on-site to ensure nothing is missed, and handle supplements when the initial approval falls short. You pay your deductible — we handle everything else.",
    process: [
      { step: "Free Damage Assessment", desc: "We inspect your entire exterior — roof, siding, gutters, windows, paint — and document every point of storm damage." },
      { step: "Claim Filing Support", desc: "We help you file your claim with properly formatted documentation that adjusters need to approve your project." },
      { step: "Adjuster Meeting", desc: "We meet your insurance adjuster on-site, walk the property together, and ensure every item of damage is accounted for." },
      { step: "Restoration Work", desc: "Once approved, we complete all restoration work to the same certified standards as any other project." },
      { step: "Supplements & Completion", desc: "If additional damage is found during restoration, we prepare and submit supplements with documentation for approval." },
    ],
    faqs: [
      { q: "Do I have to use the contractor my insurance company recommends?", a: "No. You have the legal right to choose your own contractor. Insurance-recommended contractors work for the insurance company's preferred vendor program — we work for you." },
      { q: "What is a supplement?", a: "A supplement is a request for additional funds when the initial insurance approval doesn't cover the full scope of necessary work. Common reasons include hidden deck damage, code upgrades, and items the adjuster missed." },
      { q: "How long does the insurance process take?", a: "From claim filing to completed restoration, most projects take 4-8 weeks. The timeline depends on your insurance company's response time and scheduling." },
      { q: "Will my premium go up if I file a claim?", a: "Colorado law prohibits insurers from raising rates solely because you filed a weather-related claim. However, area-wide rate increases after major storms do happen regardless of whether you file." },
      { q: "What if I already have an estimate from another contractor?", a: "We're happy to provide a second opinion. Bring us the estimate and we'll compare it to what we find. Our inspections are free and there's no obligation." },
    ],
  },
  {
    service: "Metal Roofing",
    slug: "metal-roofing",
    parentSlug: "roof-replacement",
    shortDesc: "Standing seam and metal shingle roofing systems built to handle Colorado's extreme weather.",
    longDesc: "Metal roofing is increasingly popular among Colorado homeowners who want the ultimate in durability and longevity. A properly installed standing seam or metal shingle roof can last 50+ years, withstand Class 4 hail impacts, shed snow efficiently, and provide superior fire resistance — all critical factors for Front Range and mountain properties.\n\nGates Enterprises installs standing seam, metal shingle, and metal tile roofing systems in a variety of profiles and colors. Metal roofing is particularly well-suited for Colorado because it reflects UV radiation (reducing cooling costs), handles dramatic temperature swings without damage, and can shed heavy snow loads that would stress conventional shingle systems. For homeowners tired of replacing their roof every 15-20 years after hail events, metal is the long-term solution.",
    process: [
      { step: "Consultation & Design", desc: "We assess your home's structure, discuss metal roofing profiles and colors, and ensure your home can support the system properly." },
      { step: "Structural Verification", desc: "Metal roofing requires proper substrate and ventilation. We verify or upgrade the deck, underlayment, and ventilation system." },
      { step: "Precision Installation", desc: "Standing seam panels are custom-fabricated to your roof dimensions. Each panel is secured with concealed fasteners that allow thermal expansion." },
      { step: "Flashing & Detail Work", desc: "Metal roofing lives and dies by its flashing details. We fabricate custom flashings for every transition, penetration, and edge condition." },
      { step: "Final Inspection", desc: "Complete walkthrough and manufacturer warranty registration. Metal roofs typically come with 40-50 year paint warranties and lifetime structural warranties." },
    ],
    faqs: [
      { q: "Is metal roofing louder in rain and hail?", a: "Modern metal roofing installed over solid decking and underlayment is no louder than asphalt shingles. The solid substrate absorbs sound. You won't hear rain any more than with a conventional roof." },
      { q: "How much does metal roofing cost compared to shingles?", a: "Metal roofing typically costs 2-3 times more than asphalt shingles upfront. However, with a lifespan of 50+ years versus 15-25 years for shingles, the lifetime cost is often lower — especially in Colorado where hail frequently shortens shingle life." },
      { q: "Can metal roofing handle Colorado hail?", a: "Standing seam metal roofing exceeds Class 4 impact resistance standards. While extreme hail may cause cosmetic denting, metal roofs maintain their waterproofing integrity through impacts that would destroy asphalt shingles." },
      { q: "Does metal roofing work in snowy areas?", a: "Metal roofing excels in snow. The smooth surface sheds snow efficiently, and we install snow guards where needed to prevent sudden avalanches over doorways and walkways." },
      { q: "Will a metal roof affect my home's resale value?", a: "Metal roofing adds value. Buyers recognize the longevity, durability, and low maintenance benefits. In hail-prone Colorado markets, a metal roof can be a significant selling point." },
    ],
  },
];

// ---------------------------------------------------------------------------
// HELPER: Find nearby cities (within ~30 miles)
// ---------------------------------------------------------------------------
function haversine(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 3959; // miles
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

export function getNearbyCities(citySlug: string, maxDistance = 30, limit = 8): CityData[] {
  const city = cities.find((c) => c.slug === citySlug);
  if (!city) return [];
  return cities
    .filter((c) => c.slug !== citySlug)
    .map((c) => ({ city: c, distance: haversine(city.lat, city.lon, c.lat, c.lon) }))
    .filter((c) => c.distance <= maxDistance)
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit)
    .map((c) => c.city);
}

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find((s) => s.slug === slug);
}
